config/routes.rb
Mp3app::Application.routes.draw do
      match "songs/upload", :as => "upload"  
    match "songs/delete", :as => "delete"  
    root :to => "songs#index"  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  BUCKET='books'
  def index  
    @songs = AWS::S3::Bucket.find(BUCKET).objects  
  end  
  def upload  
    begin  
      AWS::S3::S3Object.store(sanitize_filename(params[:mp3file].original_filename), params[:mp3file].read, BUCKET, :access => :public_read)  
      redirect_to root_path  
    rescue  
      render :text => "Couldn't complete the upload"  
    end  
  end  
  def delete  
    if (params[:song])  
      AWS::S3::S3Object.find(params[:song], BUCKET).delete  
      redirect_to root_path  
    else  
      render :text => "No song was found to delete!"  
    end  
  end  
  private  
  def sanitize_filename(file_name)  
    just_filename = File.basename(file_name)  
    just_filename.sub(/[^\w\.\-]/,'_')  
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
    def download_url_for(song_key, bucketid)  
        AWS::S3::S3Object.url_for(song_key, bucketid, :authenticated => false)  
    end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mp3app</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
      <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %>  
    
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/delete.html.erb
<h1>Songs#delete</h1>
<p>Find me in app/views/songs/delete.html.erb</p>

app/views/songs/index.html.erb
    <h2>Listen to a MP3 with HTML5 Audio</h2>  
    <section id="audio">  
    </section>  
    <h2>Upload a new MP3</h2>  
    <%= form_tag upload_path, :method => "post", :multipart => true do %>  
        <%= file_field_tag "mp3file" %>  
        <%= submit_tag "Upload" %>  
    <% end %>  
    <h2>Download and Delete Existing MP3's</h2>  
    <table>  
    <% @songs.each do |song| %>  
        <tr>  
            <td><%= song.key %></td>  
            <td><%= link_to "HTML5 Audio", download_url_for(song.key,'books'), :class => "html5" %></td>  
            <td><%= link_to "Download", download_url_for(song.key,'books') %></td>             
            <td><%= link_to "Delete",  "songs/delete/?song=" + song.key, :confirm => 'Are you sure you want to delete ' + song.key + '?' %></td>  
        </tr>  
    <% end %>  
    </table>  
     <script type="text/javascript">
         $(document).ready(function() {  
        var audioSection = $('section#audio');  
        $('a.html5').click(function() {  
            var audio = $('<audio>', {  
                 controls : 'controls'  
            });  
            var url = $(this).attr('href');  
            $('<source>').attr('src', url).appendTo(audio);  
            audioSection.html(audio);  
            return false;  
        });  
    });  
    </script>

app/views/songs/upload.html.erb
<h1>Songs#upload</h1>
<p>Find me in app/views/songs/upload.html.erb</p>